AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'lib/tasks/auto_annotate_models.rake'

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'Gemfile'
    - 'db/migrate/*'
    - 'config/**/*'
    - 'spec/**/*'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/StringLiterals:
  Exclude:
    - 'Gemfile'
    - 'config/**/*'

Style/SymbolArray:
  Exclude:
    - 'config/initializers/filter_parameter_logging.rb'
